footprint: [[0.15, 0.15], [0.15, -0.15], [-0.15, -0.15], [-0.15, 0.15]] 

obstacle_range: 2.5
raytrace_range: 3.0

static_layer:
  enabled: true


obstacle_layer:
  enabled: true
  track_unknown_space: true
  combination_method: 1

  obstacle_range: 2.5
  raytrace_range: 3.0

  observation_sources: scan camera
  scan: {
    data_type: LaserScan,
    topic: scan,
    marking: true,
    clearing: true
  }

  camera: {
    data_type: PointCloud2,
    topic: /tianracer/real_sense/depth/points,
    marking: true,
    clearing: true,
    max_obstacle_height: 1.5,
    min_obstacle_height: 0.2
  }
